name: .NET Core CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4  # Update to the latest version

    - name: Set up .NET
      uses: actions/setup-dotnet@v4  # Update to the latest version
      with:
        dotnet-version: 7.x  # Replace with your .NET version

    - name: Install dependencies
      run: dotnet restore YourSolutionName.sln

    - name: Build
      run: dotnet build YourSolutionName.sln --configuration Release --no-restore

    - name: Run Tests
      run: dotnet test YourSolutionName.sln --no-restore --verbosity normal
